"""
Name: Julian Jordan
Date: 10/28/2024
Assignment: Assignment # 4
Due Date: 10/30/2024
About this project: This assignment allows us to practice socket program by 
writing a simple game over a socket connection
Assumptions: Assumes players take turns nicely and in order
All work below was performed solely by Julian Jordan.
I did not use code generated by an AI tool.
Assignment done solo
"""
from socket import *
import tic_tac_toe
import sys

port = sys.argv[1]
h = gethostname()
s = socket()
print(sys.argv[0], sys.argv[1])
s.bind((h, int(port)))
s.listen(1)

while True:
	game_board = [
	['.', '.', '.'],
	['.', '.', '.'],
	['.', '.', '.']
]
	print("Waiting for opponent to connect....")
	conn, addr = s.accept()
	print("Receive opponent connection from ", addr)
	tic_tac_toe.print_board(game_board)
	print("Waiting for opponent's first move. Don't type anything!")
	opp_move = conn.recv(1000)
	tic_tac_toe.change_board(game_board, opp_move.decode(), "#")
	tic_tac_toe.print_board(game_board)
	move = input(f"Your opponent played {opp_move.decode()}, your move([ABC][123]): ")
	move = tic_tac_toe.move_valid(game_board, move)
	tic_tac_toe.change_board(game_board, move, "O")
	tic_tac_toe.print_board(game_board)
	conn.send(move.encode())
	while True:
		opp_move = tic_tac_toe.opp_move(game_board, conn, "#")
		if tic_tac_toe.game_over(game_board, "O", "#"):
			break
		tic_tac_toe.player_move(game_board, conn, "O", opp_move)
		if tic_tac_toe.game_over(game_board, "O", "#"):
			break



		
	
