"""
Name: Julian Jordan
Date: 10/28/2024
Assignment: Assignment # 4
Due Date: 10/30/2024
About this project: This assignment allows us to practice socket program by 
writing a simple game over a socket connection
Assumptions: Assumes players take turns nicely and in order
All work below was performed solely by Julian Jordan.
I did not use code generated by an AI tool.
Assignment done solo
"""
import socket
import sys
import tic_tac_toe

s = socket.socket()
game_board = [
	['.', '.', '.'],
	['.', '.', '.'],
	['.', '.', '.']
]

try:
    s.connect((sys.argv[1], int(sys.argv[2])))
except socket.error as errorMessage:
    print(f'failed to connect. {errorMessage}')
    exit()

tic_tac_toe.print_board(game_board)
move = input(("Enter a move([ABC][123]): "))
move = tic_tac_toe.move_valid(game_board, move)
tic_tac_toe.change_board(game_board, move, "#")
s.send(move.encode())
print("Waiting for opponent's move. Don't type anything!")
opp_move = s.recv(1000)
tic_tac_toe.change_board(game_board, opp_move.decode(), "O")

while True:
    tic_tac_toe.player_move(game_board, s, "#", opp_move)
    if tic_tac_toe.game_over(game_board, "#", "O"):
        break
    opp_move = tic_tac_toe.opp_move(game_board, s, "O")
    if tic_tac_toe.game_over(game_board, "#", "O"):
        break